package com.gnuey.one.storage.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gnuey.one.bean.activity.read.PlayAudioBean;

import com.gnuey.one.storage.db.greendao.PlayAudioBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playAudioBeanDaoConfig;

    private final PlayAudioBeanDao playAudioBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playAudioBeanDaoConfig = daoConfigMap.get(PlayAudioBeanDao.class).clone();
        playAudioBeanDaoConfig.initIdentityScope(type);

        playAudioBeanDao = new PlayAudioBeanDao(playAudioBeanDaoConfig, this);

        registerDao(PlayAudioBean.class, playAudioBeanDao);
    }
    
    public void clear() {
        playAudioBeanDaoConfig.clearIdentityScope();
    }

    public PlayAudioBeanDao getPlayAudioBeanDao() {
        return playAudioBeanDao;
    }

}
